/*
 * TAKESHI ME AJDUA SERIO FICOU UM LIXO EU NAO CONSEGUI FAZER DEPOIS DE 3 PROJETOS E A PRIMEIRA VEZ QUE ISSO OCORRE
 * JA ESTAVA ME SENTINDO UM PROGRAMADOR DE BOSTA AGORA PIOROU TUDO ME PERDOE FIZ TUDO ERRADO NUNCA MAIS JOGO NA SUA AULA PENSEI QUE ERA DE BOA MAIS ME FODI
 * EU ODEIO RELAY EU ODEIO REYCAST VOUDEVEORAR ESSA MERDA NAS FEIRA ME PERDOA E SERIO CARA QUE RAIVA  * 
 * ESSE PROJETO DEU TUDO ERRADO JA EWSTAVA DESANIMADO COMIGO MEESMO POR NAO CONSEGUIR FAZER NADA MAIS DIREITO
 * VOU TER QUE PEGAR ESSAS FERIA SPARA ME ALIMENTAR DE C# PROGRAMACAO POR QEU E A MIKNHA PROFISSAO QUE QUERIO SEGUIR MAS ME SINTO MUIT MAL COMIGO MESMO E ALGO PESSOAL
 * JA UE ME SINTO UM LIXO E SO UM DESABAFOE UM PEDIDO DE DESCULPASS EU VOU MELHORAR E FOCAR NO SUPER RAFAEL 69 DE VOLTA POR QUE EU SEI FAZER MAS PARECE QUE NESE SANO NADA
 * ESTA DANDO SERTO DESCULPOE POR ESSA MERDA DE DESCULPA S E ESSAA BOSTA DE TREABALHO ME PERDOE EU VOU COMPENSAR TUDO POIS EU ACREDITO QUE SOU UM BOM PROGRAMADOR SO PRECISO MELHORAR
 * UM POUCO DA CABECA PARAR DE PROCRASTINAR E FOCAR 100% DDESCULPE!
 * 
 * 
 * 
 * 
 * 
 * 
 * /